### ISSUE TITLE
/system/bin/sh: adb: not found - Error

### ISSUE THREAD

**Issue by mac89muc** [om2804/ioBroker.adb#10]
Hello - I'm running ioBroker on a Mac.
When I'm trying to send an shell command to my android device I'm getting the following error in the results dp - /system/bin/sh: adb: not found

I found out that this might be related to - adb is not at my path where the shell looks for executables.

So I edited my /.bash_profile and added the following rows

export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"

But the error still remains.
When I'm trying to send the adb commands directly from the terminal - it works without problems.

Is it possible that the error is occurring because of the iobroker user?

Any suggestions are appreciated

-------

Hallo,
ich nutze ioBroker auf meinem Mac mini.
Wenn ich versuche ein shell command an mein Android Gerät zu senden, erhalte ich den Fehler  /system/bin/sh: adb: not found - im results Datenpunkt

Ich habe herausgefunden, dass der Fehler wohl daher kommt, da adb nicht in meinem path hinterlegt ist.

Also habe ich mein /.bash_profile editiert und die folgenden Zeilen hinzugefügt:

export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"

Allerdings bleibt der Fehler anschließend erhalten - wenn ich die adb Befehle direkt über das Terminal abschicke funktioniert es aber nun.

Kann es sein, dass es am iobroker user liegt und die Zuordnung zum Path deswegen nicht greift?

Bin über Tipps dankbar, wie ich den Adapter mit meinem Mac mini zum laufen bekomme.

**Versions:**  
 - Adapter version: 0.0.6
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: Mojave 10.14.6

**Comment by om2804** [comment]
@mac89muc  Is the ADB server launched?
Apparently, a problem with a network connection arises and an attempt to launch the ADB server occurs.
Try manually start adb server: _adb start-server_

**Comment by mac89muc** [comment]
thanks for your fast reply & sorry for the dumb question - where I've to write the "add start-server" command?
if I write it in the shell dp I get the same error - /system/bin/sh: adb: not found

I think this problem is related to the missing link to the adb directory???

because I'm running iobroker under Mac OS the installation path is /usr/local/iobroker not /opt/iobroker/ like the linux installation. 
maybe that's the reason?

**Comment by om2804** [comment]
Unfortunately, I was not dealing with Mac OS.
Where is your ADB installed?

**Comment by mac89muc** [comment]
The installation path of the iobroker adb adapter is /usr/local/iobroker/node_modules/iobroker.adb

**Comment by om2804** [comment]
iobroker.adb adapter does not include adb server. It is necessary to install separately. See Readme

**Comment by mac89muc** [comment]
sorry - I thought you're talking about the adb adapter under Mac OS.

Android SDK Location is - /Users/myuser/Library/Android/sdk

**Comment by mac89muc** [comment]
Ok - got it working.
I placed the same command in the shell dp as in the terminal - e.g. adb shell input keyevent "KEYCODE_POWER"
I didn't noticed that I have to remove "adb" in the front of the command.

so when I write - shell input keyevent "KEYCODE_POWER" it's working.

bit confusing....
