### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [om2804/ioBroker.adb#2]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/om2804/ioBroker.adb

- [x] [E150] No common.connectionType found in io-package.json
- [x] [E152] No common.dataSource found in io-package.json
- [x] [E605] No actual year found in copyright. Please add "Copyright (c) 2021 om2804 <om2804@mail.ru>" at the end of README.md
- [x] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2021 om2804 <om2804@mail.ru>" at the start of LICENSE

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by om2804** [comment]
>

**Comment by om2804** [comment]
> Do you need help fixing the bugs?


Yes. What values to install in common.connectionType and common.dataSource?

**Comment by Apollon77** [comment]
see https://github.com/ioBroker/ioBroker.repositories#connection-types

**Comment by om2804** [comment]
> 


> see https://github.com/ioBroker/ioBroker.repositories#connection-types

Thanks
