### ISSUE TITLE
Screencap nicht möglich

### ISSUE THREAD

**Issue by djmarc75** [om2804/ioBroker.adb#9]
Screencapture wird beim Ausführen mit folgendem LOG quittiert und keine Datei (*.png) gespeichert:

`Cannot write file /screenshot.png: adb.0 is not an object of type "meta"`

 - Adapter version: 0.0.6
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: debian bullseye

**Comment by om2804** [comment]
@djmarc75 Please, try bugfix. Install from custom url  https://github.com/om2804/ioBroker.adb#issue_9

**Comment by djmarc75** [comment]
@om2804 Done, but still same Error in LOG.

**Comment by om2804** [comment]
@djmarc75 I updated version. Please update adapter to 0.0.7 ver.

**Comment by djmarc75** [comment]
@om2804 update has solved the problem.
Thank you for this great job !
